apiVersion: v1
kind: ConfigMap
metadata:
  name: web-service-config
data:
  APP_PORT: "3000"
  APP_LOG: "web_service=debug,tower_http=debug,axum::rejection=debug,tower_http::trace::make_span=debug,sqlx=debug"
  PG_DATABASE_HOST: "postgres"
  PG_DATABASE_PORT: "5432"
  PG_DATABASE_DB: "apidb"
  PG_DATABASE_USERNAME: "postgres"
